name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 2.1.0
publish_to: none
homepage: git@github.com:sergey-s-moiseev/flutter_map_location_marker.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass:
    git:
      url: git@github.com:sergey-s-moiseev/flutter_compass.git
  flutter_map: ^0.14.0
  geolocator: ^8.0.3
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
